version: '3.8'

services:
  local-llm:
    build: ./local_llm_service
    ports:
      - "8080:80"
    networks:
      - code-review-network

  llm-service:
    build: ./llm_service
    ports:
      - "8000:8000"
    environment:
      - LLM_PROVIDER=local
      - LOCAL_MODEL_URL=http://local-llm:80
    depends_on:
      - local-llm
    networks:
      - code-review-network

  code-analysis-service:
    build: ./code_analysis_service
    ports:
      - "8001:8000"
    environment:
      - REPO_STORAGE_PATH=/repos
      - LLM_SERVICE_URL=http://llm-service:8000
    volumes:
      - repo-data:/repos
    depends_on:
      - llm-service
      - redis
    networks:
      - code-review-network

  code-analysis-worker:
    build: ./code_analysis_service
    command: celery -A app.tasks worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - repo-data:/repos
    depends_on:
      - redis
    networks:
      - code-review-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - code-review-network

volumes:
  repo-data:

networks:
  code-review-network:
    driver: bridge 